### ISSUE TITLE
Server seems stuck

### ISSUE THREAD

**Issue by bakkot** [verbiageecstatic/SlateStarCommentServer#5]
Not sure if you're around anymore, but in case you are - the server seems to have gotten stuck a few months ago, per the health page: http://sscnotify.bakkot.com

**Comment by verbiageecstatic** [comment]
Yep, I still exist :).  I noticed it went down and plan to take a look, but
it’s been a very busy few months for me.  Also, do you know if people are
actually using this? If people are getting value out of it, that’s more
motivation for me to make the time...

**Comment by bakkot** [comment]
Evidently, since [that's how I heard about it!](https://slatestarcodex.com/2019/03/10/ot123-oped-thread/#comment-729280)

It continues to be very poorly advertised, but I'm considering taking a few days sometime soon to work through my backlog of improvements, which would include advertising it in every comment thread.

**Comment by verbiageecstatic** [comment]
Okay, I’ll see what I can do this weekend!

**Comment by verbiageecstatic** [comment]
Okay, fixed it!  The switch from http -> https broke things; I a) switched the url we hit, and b) updated the curl command to follow redirects so next time something changes it'll be more likely to survive.

**Comment by bakkot** [comment]
:D Thanks!
